### ISSUE TITLE
魔改BIOS是否支持黑苹果?

### ISSUE THREAD

**Issue by lclancey** [Jiangtaste/i5-6500-Maximus-viii-gene-Hactintosh#1]
请问如题 我一直挺好奇这个问题的
主要是没见过同时魔改BISO+黑果的, 是难度高或者做不到吗?

**Comment by jiangtaste** [comment]
简单说：支持

我这块板子正使用的就是魔改过的BIOS，但是手上只有i5 6500的U，理论上8和9代的U也是无痛升级的。这个就待你自己实验了。

**Comment by tanpengsccd** [comment]
m8r 好像和这个板子很像。想试试 魔改板+魔改U的极限组合。
