### ISSUE TITLE
关于macOS版本

### ISSUE THREAD

**Issue by zzeng12** [Jiangtaste/i5-6500-Maximus-viii-gene-Hactintosh#2]
你好  想问一下 你装的苹果系统是哪个版本呢？

**Comment by jiangtaste** [comment]
当前：10.15.3

**Comment by zzeng12** [comment]
我主板是魔改的m8i 9100f的u 尝试引导启动 会出现Error loading kernel cache（0xc），用clover会macOS not set，暂时还没找到原因，以你的经验会是哪块的问题，我尝试把acpi里边的补丁去掉引导进度会稍微发生一些变化，但最终还是会出现上面的情况。另外，你装的时候是用的usb2.0接口么，m8i上没有2.0的接口。

**Comment by jiangtaste** [comment]
我的黑果多年前都稳定下来了，最近的折腾都是让它更完美，所以对这些报错没啥印象了。帮你查了下Error loading kernel cache（0xc），似乎是fusion driver使用apfs安装系统的问题。我的板子没有usb2.0接口。

**Comment by zzeng12** [comment]
好，麻烦了，我继续尝试一下

**Comment by lclancey** [comment]
> 好，麻烦了，我继续尝试一下

老哥试出结果了吗

**Comment by zzeng12** [comment]
> > 好，麻烦了，我继续尝试一下
> 
> 老哥试出结果了吗

目前使用10.14.6可以正常安装,还有一些小问题正在调试,10.15.3还是安装不了，用楼主的OC也可以引导10.14.6进系统,回头看看10.15到底啥问题 按理m8g可以，m8i应该也可以的

**Comment by zzeng12** [comment]
> 当前：10.15.3

对了，华硕这一代m8系列170主板,支持原生nvram不,你是否知道相关信息，另外,要看CPU是否正常睿频，应该用什么方法或工具

**Comment by jiangtaste** [comment]
> > 当前：10.15.3
> 
> 对了，华硕这一代m8系列170主板,支持原生nvram不,你是否知道相关信息，另外,要看CPU是否正常睿频，应该用什么方法或工具

1. 原生支持nvram
2. 有多种工具，inter官方有一个：[Inter Power Gadget](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjyis_C4v_nAhVKnJ4KHQpzDMcQFjAAegQIAhAB&url=https%3A%2F%2Fsoftware.intel.com%2Fen-us%2Farticles%2Fintel-power-gadget&usg=AOvVaw0FQc2UjFWXr-4KZ3CmOn-k)

**Comment by zzeng12** [comment]
好，感谢

**Comment by wintry** [comment]
> > > 好，麻烦了，我继续尝试一下
> > 
> > 
> > 老哥试出结果了吗
> 
> 目前使用10.14.6可以正常安装,还有一些小问题正在调试,10.15.3还是安装不了，用楼主的OC也可以引导10.14.6进系统,回头看看10.15到底啥问题 按理m8g可以，m8i应该也可以的

有新进展求efi
