### ISSUE TITLE
是否支持6700k和10.15.7

### ISSUE THREAD

**Issue by vaithwee** [Jiangtaste/i5-6500-Maximus-viii-gene-Hactintosh#3]
我是用Clover安装和引导的, CPU是6700k, 系统是10.15.7, 想问下是否能通过你的这个配置OC引导, 我电源管理有点问题, Clover有点麻烦

**Comment by jiangtaste** [comment]
你先尝试iMac EFI 17,1 这个目录的oc启动文件看是否能启动你现在的10.15.7。
这个目录时我之前i5 6500时的配置，如果可以，则自行使用iMac EFI 19,1 这个目录的配置，你需要修改config.plist中的机型为iMac 17,1

**Comment by jiangtaste** [comment]
无新的疑问
