### ISSUE TITLE
楼主用的什么版本的bios

### ISSUE THREAD

**Issue by xratzh** [Jiangtaste/i5-6500-Maximus-viii-gene-Hactintosh#4]
http://www.smxdiy.com/thread-1407-1-1.html
我用的这个版本的，3801的稳定修改版，似乎在Windows和mac下，休眠都不能唤醒

**Comment by jiangtaste** [comment]
也是3801，我这边mac下工作正常。未安装过windows，不清楚。

**Comment by xratzh** [comment]
@Jiangtaste 楼主是自己修改的么？求分享一下你的BIOS文件，我的邮箱xratzh#gmail.com。目前我用的帖子里面的两个都不能睡眠唤醒，这个问题困扰很久了，一直以为是都这样。谢谢

**Comment by jiangtaste** [comment]
就是d大发的那个bios。睡眠唤醒应该和bios无关的。

**Comment by jiangtaste** [comment]
没事儿了
