### ISSUE TITLE
EFI-iMAC17,1的能直接用来安装Monterey吗？

### ISSUE THREAD

**Issue by Yefee** [Jiangtaste/i5-6500-Maximus-viii-gene-Hactintosh#5]
如题，谢谢！

**Comment by Yefee** [comment]
用19，1解决了

**Comment by jiangtaste** [comment]
我在Big Sur版本后，这台主机就闲置了，所以没有更新EFI配置文件，不清楚是否能安装Monterey。见你已成功安装Monterey，如能稳定使用，则无须改动配置，如无法稳定使用，可自行研究并更新OpenCore版本即可。
